keyMirror = require 'keymirror'

module.exports = keyMirror
  CREATE_TERM: null
  CREATE_PERMANENT_TERM: null
  DELETE_TERM: null
  CHANGE_TERM_CATEGORY: null
  CHANGE_TERM_VALUE: null
  UPDATE_FACETS: null
  OVERRIDE_SEARCH: null
  SEARCHBAR_SETUP_COMPLETE: null
  SEARCHBAR_ACTIVATE_ROUTING: null
  SEARCHBAR_FORCE_LOCATION_CHANGE: null
  UPDATE_PAGINATION_OFFSET: null
  SUBSCRIPTION_PROHIBITED_REASON_NO_LLP: null
  SUBSCRIPTION_PROHIBITED_REASON_NEED_MORE_FACETS: null
  SUBSCRIPTION_ALLOWED: null
